### ISSUE TITLE
Commits, Contributors and Releases data

### ISSUE THREAD

**Issue by a-jackson** [RobbieLD/github-portfolio#1]
I have hooked up the projects with the data that we have in the GithubRepo object but there are several fields that are not available.

We can get this data but may run into issues with rate limiting on the GIthub API.

![image](https://user-images.githubusercontent.com/2199309/54069246-1cd34180-424e-11e9-9318-7c3c463b9702.png)

The 3 missing fields are number of commits, releases and contributors. There are no counts of this data available but we can get all the data and count it ourselves. The problem it is paged.

e.g. 
https://api.github.com/repos/RobbieLD/github-portfolio/commits?per_page=5
Gives us the first 5 commits (obviously we can say more than 5 but there's only 17 commits currently and this give us multiple pages)

This also has the Link header in the response with the value
`<https://api.github.com/repositories/173989281/commits?per_page=5&page=2>; rel="next", <https://api.github.com/repositories/173989281/commits?per_page=5&page=4>; rel="last"`

This gives us the link the next page and the last page. We can go the last page and see there are 2 commits and infer 3 full pages of 5 each before that and get 17 commits total. 

If the Link header is absent then all the data is on page 1. This still means 6 requests per repo to get all the data we want. 
Might be easier to just not include it?

**Comment by RobbieLD** [comment]
Nice work. I just added all those icons in to see how they look. I'm really not bothered about removing ones we can' easily populate.

**Comment by a-jackson** [comment]
I've removed the extra links.
